// Datos iniciales (semilla) del directorio de parroquias, rectorías y capillas
// de la Arquidiócesis de Toluca, agrupadas por decanato y zona pastoral.
// Fuente: "Directorio - Ubica tu Decanato.pdf".
//
// Este archivo solo se usa para poblar la base de datos la primera vez que se
// ejecuta la app. Una vez sembrado, el directorio se administra y edita desde
// el panel de organizadores (/admin/directorio), no desde este archivo.
export type SeedGroup = {
  id: string;
  decanato: string;
  zonaPastoral: string;
  parishes: [name: string, locality: string][];
};

export const SEED_GROUPS: SeedGroup[] = [
  {
    id: "d01",
    decanato: "San José",
    zonaPastoral: "San Pedro Apóstol",
    parishes: [
      ["Rectoría de María, Reina de la Paz", "Toluca"],
      ["Parroquia de Nuestra Señora de Guadalupe", "Toluca"],
      ["Parroquia de San Juan Bautista", "Toluca"],
      ["Rectoría de San Diego de Alcalá", "Toluca"],
      ["Rectoría de Santa Clara de Asís", "Toluca"],
      ["Parroquia de La Virgen de Guadalupe y San Juan Diego", "Toluca"],
      ["Capilla de La Magdalena", "Tlacopa, Toluca"],
      ["Parroquia de Nuestra Señora de los Ángeles", "Huitzila, Toluca"],
      ["Parroquia de Santiago Apóstol", "Santiago Miltepec, Toluca"],
      ["Capilla de Nuestra Señora de Guadalupe", "Rancho la Mora, Toluca"],
      ["Rectoría de Nuestra Señora de Lourdes", "Toluca"],
      ["Rectoría de San Juan Evangelista", "San Juan Chiquito, Toluca"],
      ["Parroquia de San José, El Sagrario", "Toluca"],
      ["Rectoría de La Santa Veracruz", "Toluca"],
      ["Rectoría de Nuestra Señora del Carmen", "Toluca"],
      ["Parroquia y Templo Expiatorio Diocesano Santa Bárbara", "Toluca"],
      ["Rectoría de San Miguel Arcángel", "San Miguel Apinahuizco, Toluca"],
      ["Parroquia de La Santa Cruz", "Santa Cruz Atzcapotzaltongo, Toluca"],
      ["Capilla de Santiago", "Tlaxomulco, Toluca"],
      ["Parroquia de San Francisco de Asís", "Calixtlahuaca, Toluca"],
    ],
  },
  {
    id: "d02",
    decanato: "San Carlos Borromeo",
    zonaPastoral: "San Pedro Apóstol",
    parishes: [
      ["Rectoría de Nuestra Señora de los Dolores", "Toluca"],
      ["Rectoría de San José", "El Ranchito, Toluca"],
      ["Parroquia de La Divina Providencia", "Toluca"],
      ["Capilla del Señor de la Redención", "Toluca"],
      ["Parroquia de San Felipe de Jesús", "Toluca"],
      ["Parroquia de Nuestra Señora de los Desamparados", "Toluca"],
      ["Rectoría de El Calvario", "Toluca"],
      ["Parroquia y Santuario de Santa María de Guadalupe", "Toluca"],
      ["Rectoría y Santuario de Nuestra Señora de la Merced", "Toluca"],
      ["Parroquia de San Bernardino de Siena", "Toluca"],
      ["Parroquia Universitaria María, Madre de la Sabiduría", "Toluca"],
      ["Parroquia de El Patrocinio de San José", "Toluca"],
      ["Parroquia de San Mateo Apóstol", "Oxtotitlán, Toluca"],
      ["Parroquia de Nuestra Señora del Rosario de Fátima", "Toluca"],
      ["Parroquia de Cristo Rey", "Toluca"],
    ],
  },
  {
    id: "d03",
    decanato: "San Pío X",
    zonaPastoral: "San Pedro Apóstol",
    parishes: [
      ["Parroquia de El Señor de la Transfiguración", "Metepec"],
      ["Rectoría de San Judas Tadeo, Apóstol", "Metepec"],
      ["Parroquia de La Inmaculada Concepción de María", "Metepec"],
      ["Rectoría de El Señor de la Misericordia", "Toluca"],
      ["Parroquia de La Santa Cruz Gloriosa", "Toluca"],
      ["Parroquia de Jesús Nazareno", "Toluca"],
      ["Rectoría de El Espíritu Santo", "Toluca"],
      ["Rectoría de Santos Simón y Judas Tadeo, Apóstoles", "Toluca"],
      ["Parroquia de San Martín de Porres", "Toluca"],
      ["Rectoría de La Sagrada Familia", "Toluca"],
      ["Parroquia de San Sebastián", "Toluca"],
      ["Parroquia de Nuestra Señora del Perpetuo Socorro", "Toluca"],
      ["Parroquia de Nuestra Señora del Sagrado Corazón", "Toluca"],
      ["Parroquia de Nuestra Señora de Fátima", "Toluca"],
      ["Parroquia de Santa María de las Rosas", "Toluca"],
    ],
  },
  {
    id: "d04",
    decanato: "San Agustín de Hipona",
    zonaPastoral: "San Andrés Apóstol",
    parishes: [
      ["Capilla de El Divino Salvador", "San Salvador Tizatlali"],
      ["Parroquia de San Jerónimo", "San Jerónimo Chicahualco, Metepec"],
      ["Rectoría de Nuestra Señora del Perpetuo Socorro", "Metepec"],
      ["Parroquia de San José Obrero", "Metepec"],
      ["Capilla de La Santa Cruz", "Santa Ana Tlapaltitlán"],
      ["Capilla de Santa María Zozoquipan", "Santa Ana Tlapaltitlán"],
      ["Parroquia de San Gabriel Arcángel", "Fuentes de San Gabriel, Infonavit, Metepec"],
      ["Parroquia de San Carlos Borromeo", "Metepec"],
      ["Rectoría de San Francisco de Asís", "San Francisco Coaxusco, Metepec"],
      ["Parroquia de Santa Ana", "Santa Ana Tlapaltitlán, Toluca"],
    ],
  },
  {
    id: "d05",
    decanato: "San Juan Bautista",
    zonaPastoral: "San Andrés Apóstol",
    parishes: [
      ["Parroquia y Santuario de Nuestra Señora de la Vida", "Metepec"],
      ["Parroquia de San Miguel Arcángel", "San Miguel Totocuitlapilco, Metepec"],
      ["Parroquia de San Bartolomé Apóstol", "San Bartolomé Tlaltelulco, Metepec"],
      ["Parroquia de Santa María Magdalena", "Ocotitlán"],
      ["Parroquia de San Juan Bautista y Santa María de Guadalupe", "Metepec"],
      ["Rectoría de La Anunciación", "La Virgen, Metepec"],
      ["Parroquia de San José", "Rancho La Pila, Metepec"],
      ["Parroquia de La Santísima Trinidad", "La Asunción, Metepec"],
      ["Parroquia de San Francisco de Asís", "Infonavit, Metepec"],
      ["Rectoría de Inmaculado Corazón de María", "Metepec"],
      ["Parroquia de Sagrado Corazón de Jesús", "Metepec"],
    ],
  },
  {
    id: "d06",
    decanato: "San Juan María Vianney",
    zonaPastoral: "San Andrés Apóstol",
    parishes: [
      ["Rectoría de San Juan Bautista", "San Juan Tilapa"],
      ["Parroquia de Santiago Apóstol", "Santiago Tlacotepec"],
      ["Parroquia de San Felipe Apóstol", "San Felipe Tlalmimilolpan"],
      ["Parroquia de El Divino Salvador", "Capultitlán"],
      ["Parroquia de Sagrado Corazón de Jesús", "Ocho Cedros"],
      ["Rectoría de Santa María de Guadalupe", "Col. Guadalupe"],
      ["Parroquia de San Buenaventura", "San Buenaventura"],
      ["Parroquia de La Asunción de María", "Cacalomacán"],
      ["Parroquia de San Antonio de Padua", "San Antonio Buenavista"],
      ["Rectoría de Nuestra Señora del Sagrado Corazón", "Cacalomacán"],
      ["Rectoría de Santa Cruz Cuauhtenco", "Santa Cruz Cuauhtenco"],
    ],
  },
  {
    id: "d07",
    decanato: "San Ignacio de Antioquia",
    zonaPastoral: "Santiago el Mayor Apóstol",
    parishes: [
      ["Parroquia de San Francisco de Asís", "San Francisco Tepexoxuca, Tenango del Valle"],
      ["Parroquia de San Pedro Apóstol", "Zictepec, Tenango del Valle"],
      ["Parroquia de San Bartolomé Apóstol", "Atlatlahuca, Tenango del Valle"],
      ["Parroquia de La Asunción de María", "Tenango del Valle"],
      ["Parroquia de San Miguel Arcángel", "San Miguel Balderas, Tenango del Valle"],
      ["Parroquia de Nuestra Señora del Pilar", "Zaragoza de Guadalupe, Calimaya"],
      ["Parroquia de San Pedro y San Pablo, Apóstoles", "Calimaya"],
      ["Parroquia de La Asunción de María", "Santa María Rayón"],
      ["Parroquia de San Antonio de Padua", "San Antonio la Isla"],
      ["Parroquia de San Andrés Apóstol", "San Andrés Ocotlán"],
      ["Parroquia de San Miguel Arcángel", "San Miguel Chapultepec"],
      ["Parroquia de San Mateo Apóstol", "Mexicaltzingo"],
      ["Parroquia de La Natividad de María", "Santa María Nativitas"],
    ],
  },
  {
    id: "d08",
    decanato: "Espíritu Santo",
    zonaPastoral: "Santiago el Mayor Apóstol",
    parishes: [
      ["Parroquia de San Pedro Apóstol", "Atlapulco, San Pedro Atlapulco"],
      ["Parroquia de El Divino Salvador", "Santiago Tilapa"],
      ["Rectoría de San Miguel Arcángel", "San Miguel Almaya"],
      ["Parroquia de San Bartolomé Apóstol", "Capulhuac"],
      ["Parroquia de Santiago Apóstol", "Santiago Tianguistenco"],
      ["Parroquia de San Pedro Apóstol", "San Pedro Tlaltizapán"],
      ["Parroquia de Santa Cruz", "Santa Cruz Atizapán"],
      ["Parroquia de San Miguel Arcángel", "Almoloya del Río"],
      ["Parroquia de San Mateo Apóstol", "San Mateo Texcalyacac"],
      ["Parroquia de San Nicolás Tolentino", "Coatepec de las Bateas, Tianguistenco"],
      ["Parroquia de La Asunción de María", "Xalatlaco"],
    ],
  },
  {
    id: "d09",
    decanato: "Santa Clara de Asís",
    zonaPastoral: "San Pablo Apóstol",
    parishes: [
      ["Parroquia de San Nicolás Tolentino", "San Nicolás Peralta, Lerma"],
      ["Parroquia de Santa María de la Asunción", "Sta. María Atarasquillo"],
      ["Parroquia de San Miguel Arcángel", "San Miguel Ameyalco, Lerma"],
      ["Parroquia de Santa Clara de Asís", "Lerma"],
      ["Parroquia de Santa Rosa de Lima", "San Mateo Atenco"],
      ["Parroquia de San José", "El Cerrillo Vista Hermosa, San Pedro Totoltepec"],
      ["Parroquia de San Pedro Apóstol", "San Pedro Totoltepec"],
      ["Parroquia de La Inmaculada Concepción", "Santa María Totoltepec"],
      ["Rectoría de Nuestra Señora del Carmen", "Sta. María Totoltepec"],
    ],
  },
  {
    id: "d10",
    decanato: "San Martín Obispo de Tours",
    zonaPastoral: "San Pablo Apóstol",
    parishes: [
      ["Parroquia de La Asunción de María", "Tepexoyuca"],
      ["Parroquia de San Martín, Obispo de Tours", "Ocoyoacac"],
      ["Rectoría de San Pedro Apóstol", "Cholula, Ocoyoacac"],
      ["Parroquia de San Pedro Apóstol", "San Pedro Tultepec"],
      ["Rectoría de San Pedro y San Pablo Atenco", "San Mateo Atenco"],
      ["Parroquia de San Mateo Apóstol", "San Mateo Atenco"],
      ["Parroquia de Nuestra Señora de Guadalupe", "San Mateo Atenco"],
      ["Parroquia de San Gaspar", "San Gaspar Tlahuelilpan, Metepec"],
      ["Parroquia de Santa María de los Ángeles", "Atenco, San Mateo Atenco"],
      ["Parroquia y Santuario de Nuestra Señora de San Juan de los Lagos", "San Mateo Atenco"],
    ],
  },
  {
    id: "d11",
    decanato: "San Bartolomé Apóstol",
    zonaPastoral: "San Mateo Apóstol y Evangelista",
    parishes: [
      ["Parroquia de Santa Ana", "Santa Ana Jilotzingo, Otzolotepec"],
      ["Parroquia de San Miguel Arcángel", "Mimiapan, Xonacatlán"],
      ["Parroquia de San Isidro Labrador", "Zacamulpa, Lerma"],
      ["Parroquia de San Lorenzo", "Huitzizilapan, Lerma"],
      ["Parroquia de San Francisco de Asís", "Xonacatlán"],
      ["Parroquia de San Bartolomé Apóstol", "Otzolotepec, Villa Cuauhtémoc"],
    ],
  },
  {
    id: "d12",
    decanato: "San Juan Diego",
    zonaPastoral: "San Mateo Apóstol y Evangelista",
    parishes: [
      ["Rectoría de San Pedro Apóstol", "San Pedro Arriba, Temoaya"],
      ["Parroquia y Santuario de Santiago Apóstol", "Temoaya"],
      ["Parroquia de San Diego de Alcalá", "Temoaya"],
      ["Rectoría de San Cayetano y San Nicolás Tolentino", "Tlachaloya Primera Sección"],
      ["Parroquia de Santa María de Guadalupe", "Taborda"],
      ["Parroquia de San Diego de Alcalá", "San Pablo Autopan"],
      ["Parroquia de San Pablo Apóstol", "San Pablo Autopan"],
      ["Parroquia de Santa María de Guadalupe", "Pueblo Nuevo, San Pablo Autopan"],
      ["Parroquia de San Andrés Apóstol", "San Andrés Cuexcontitlán"],
      ["Rectoría de San Diego de los Padres", "San Andrés Cuexcontitlán"],
      ["Parroquia de San Cristóbal", "San Cristóbal Huichochitlán"],
      ["Parroquia de San Mateo Apóstol", "San Mateo Otzacatipan"],
    ],
  },
  {
    id: "d13",
    decanato: "San Miguel Arcángel",
    zonaPastoral: "San Juan Apóstol y Evangelista",
    parishes: [
      ["Parroquia de San Mateo Apóstol", "San Mateo Tlalchichilpán"],
      ["Parroquia y Santuario de Nuestra Señora de los Ángeles", "Tecaxic"],
      ["Parroquia de El Señor de los Milagros", "Zinacantepec"],
      ["Parroquia de San Luis, Rey de Francia", "San Luis Mextepec"],
      ["Parroquia de San Miguel Arcángel", "Zinacantepec"],
      ["Parroquia de San Cristóbal", "San Cristóbal Tecolit"],
      ["Parroquia de San Juan Bautista", "San Juan de las Huertas"],
      ["Parroquia de San Antonio de Padua", "San Antonio Acahualco"],
      ["Parroquia de San Francisco de Asís", "San Francisco Tlalcilalcalpan"],
      ["Parroquia de Santa María Magdalena", "Santa María del Monte"],
    ],
  },
  {
    id: "d14",
    decanato: "San Gabriel Arcángel",
    zonaPastoral: "San Juan Apóstol y Evangelista",
    parishes: [
      ["Parroquia de San José", "Almoloya de Juárez"],
      ["Parroquia de La Inmaculada Concepción", "Mayorazgo de León"],
      ["Parroquia de San Miguel", "San Miguel Almoloyán"],
      ["Parroquia de San Nicolás Tolentino", "San Nicolás Amealco, Almoloya de Juárez"],
      ["Parroquia de San Juan María Vianney", "Cieneguillas, Almoloya de Juárez"],
      ["Parroquia del Señor de los Milagros", "Villa Victoria"],
      ["Parroquia de Nuestra Señora de la Merced", "Villa Victoria"],
      ["Parroquia de El Señor de la Preciosa Sangre", "Ayala, Villa Victoria"],
      ["Parroquia de Nuestra Señora de Guadalupe", "Yebucivi, Almoloya de Juárez"],
    ],
  },
  {
    id: "d15",
    decanato: "San Francisco de Asís",
    zonaPastoral: "Santo Tomás Apóstol",
    parishes: [
      ["Parroquia de San Jerónimo", "Amanalco de Becerra"],
      ["Parroquia de La Asunción de María", "Pipioltepec, Valle de Bravo"],
      ["Parroquia de San Francisco de Asís", "Valle de Bravo"],
      ["Santuario del Cristo Negro", "Santa María Ahuacatlán, Valle de Bravo"],
      ["Parroquia de Nuestra Señora de Fátima", "Avandaro"],
      ["Parroquia del Sagrado Corazón de Jesús", "Colorines, Valle de Bravo"],
      ["Parroquia de Santo Tomás Apóstol", "Nuevo Santo Tomás de los Plátanos"],
      ["Parroquia de San Miguel Arcángel", "Ixtapan del Oro"],
      ["Parroquia de La Asunción de María", "Malacatepec, Donato Guerra"],
      ["Parroquia de San José", "Villa de Allende"],
    ],
  },
  {
    id: "d16",
    decanato: "El Señor del Perdón y Nuestra Señora de la Consolación",
    zonaPastoral: "Santo Tomás Apóstol",
    parishes: [
      ["Parroquia de La Sagrada Familia", "Comunidad, Temascaltepec"],
      ["Parroquia de San Martín Obispo de Tours", "Tequesquipan, Temascaltepec"],
      ["Parroquia de Santos Simón y Judas Tadeo, Apóstoles", "San Simón de Guerrero"],
      ["Parroquia de El Señor del Perdón y Nuestra Señora de la Consolación", "Temascaltepec"],
      ["Parroquia de San Pedro Apóstol", "Tenayac, Temascaltepec"],
      ["Parroquia de La Inmaculada Concepción", "Cerro Colorado, Valle de Bravo"],
    ],
  },
];
